name: Clarive WebSphere Plugin
description: The Websphere plugin will allow you to manage your Websphere Application Server applications from a Clarive instance.
version: 1.0
icon: https://github.com/clarive/cla-websphere-plugin/public/icon/websphere.svg
url: https://github.com/clarive/cla-websphere-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-websphere-plugin
